name: 功能请求
description: 提出新功能建议
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你提出功能建议！请填写以下信息。

  - type: checkboxes
    id: prerequisite
    attributes:
      label: 前置确认
      options:
        - label: 我已阅读 README.md 文档
          required: true
        - label: 我已检查现有 Issues，未发现重复的功能请求
          required: true

  - type: dropdown
    id: request-type
    attributes:
      label: 请求类型
      options:
        - 新命令
        - 功能增强
        - 配置选项
        - 用户体验改进
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题或需求
      description: 这个功能请求是否与某个问题相关？
      placeholder: 当我想要...时，目前没有办法...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 描述你希望的功能或解决方案
      placeholder: 我希望能够...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你是否考虑过其他替代方案？
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 任何其他相关信息、截图等
    validations:
      required: false
