name: 问题咨询
description: 使用问题、配置疑惑等
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        有问题？请先查看 [README](https://github.com/GEMILUXVII/astrbot_plugin_jm_cosmos#readme) 和 [常见问题](https://github.com/GEMILUXVII/astrbot_plugin_jm_cosmos#常见问题) 部分。

  - type: checkboxes
    id: prerequisite
    attributes:
      label: 前置确认
      options:
        - label: 我已阅读 README.md 文档
          required: true
        - label: 我已查看「常见问题」部分
          required: true
        - label: 我已搜索现有 Issues，未找到答案
          required: true

  - type: input
    id: version
    attributes:
      label: 插件版本
      placeholder: v2.x.x
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 问题描述
      description: 详细描述你的问题
      placeholder: 我想知道如何...
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: 已尝试的方法
      description: 你已经尝试了什么？
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 截图、配置、日志等
    validations:
      required: false
